import { Model } from '@/types/model'

export const models: Model[] = [
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'google.com',
    premium: false,
    tier: 'lite',
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google.com',
    premium: false,
    tier: 'flash',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google.com',
    premium: false,
    tier: 'flash',
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    provider: 'google.com',
    premium: false,
    tier: 'lite',
  },
  // {
  //   id: 'gemini-2.0-flash-exp',
  //   name: 'Gemini 2.0 Flash Exp',
  //   premium: false,
  //   provider: 'google.com',
  //   tier: 'flash',
  // },
  // {
  //   id: 'gemini-2.0-flash-thinking-exp',
  //   name: 'Gemini 2.0 Flash Thinking Exp',
  //   premium: true,
  //   provider: 'google.com',
  //   tier: 'thinking',
  // },
  // {
  //   id: 'gemini-2.0-flash-thinking-exp-01-21',
  //   name: 'Gemini 2.0 Flash Thinking Exp 01 21',
  //   premium: true,
  //   provider: 'google.com',
  //   tier: 'thinking',
  // },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google.com',
    premium: true,
    tier: 'pro',
  },
  {
    id: 'moonshotai/kimi-k2.5',
    name: 'MoonshotAI Kimi K2.5',
    provider: 'moonshot.cn',
    premium: true,
    tier: 'pro',
  },
  {
    id: 'qwen/qwen3.5-397b-a17b',
    name: 'Qwen 3.5 397B A17B',
    provider: 'qwen.ai',
    premium: true,
    tier: 'pro',
  },
  {
    id: 'z-ai/glm5',
    name: 'GLM-5 744B',
    provider: 'z-ai.com',
    premium: true,
    tier: 'thinking',
  },
  {
    id: 'deepseek-ai/deepseek-v3.2',
    name: 'DeepSeek V3.2 685B',
    provider: 'deepseek.com',
    premium: true,
    disabled: false,
    tier: 'thinking',
  },
  {
    id: 'mistralai/mistral-large-3-675b-instruct-2512',
    name: 'Mistral Large 3 675B',
    provider: 'mistral.ai',
    premium: true,
    disabled: false,
    tier: 'pro',
  },
  {
    id: 'deepseek-ai/deepseek-v3.1-terminus',
    name: 'DeepSeek V3.1 Terminus',
    provider: 'deepseek.com',
    premium: true,
    disabled: false,
    tier: 'thinking',
  },
  {
    id: 'nvidia/llama-3.1-nemotron-ultra-253b-v1',
    name: 'Llama 3.1 Nemotron Ultra 253B',
    provider: 'nvidia.com',
    premium: true,
    disabled: false,
    tier: 'thinking',
  },
  {
    id: 'qwen/qwen3-coder-480b-a35b-instruct',
    name: 'Qwen 3 Coder 480B',
    provider: 'qwen.ai',
    premium: true,
    tier: 'pro',
  },
  {
    id: 'mistralai/devstral-2-123b-instruct-2512',
    name: 'Devstral 2 123B',
    provider: 'mistral.ai',
    premium: false,
    disabled: false,
    tier: 'flash',
  },
  {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
    name: 'Llama 3.3 Nemotron Super 49B',
    provider: 'nvidia.com',
    premium: false,
    disabled: false,
    tier: 'flash',
  },
  {
    id: 'qwen/qwen3-4b-thinking-2507',
    name: 'Qwen 3.4B Thinking 2507',
    provider: 'qwen.ai',
    premium: false,
    disabled: true,
    tier: 'thinking',
  },
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B Versatile',
    provider: 'meta.com',
    premium: false,
    disabled: true,
    tier: 'flash',
  },
  {
    id: 'mixtral-8x7b-32768',
    name: 'Mixtral 8x7B 32K',
    provider: 'mistral.ai',
    premium: false,
    disabled: true,
    tier: 'flash',
  },
  {
    id: 'gemma2-9b-it',
    name: 'Gemma 2 9B IT',
    provider: 'google.com',
    premium: false,
    disabled: true,
    tier: 'lite',
  },
  {
    id: 'groq-compound-4',
    name: 'Groq Compound 4',
    provider: 'groq.com',
    premium: false,
    disabled: true,
    tier: 'pro',
  },
]
