import { Model } from '@/types/model'

export const models: Model[] = [
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'google.com',
    premium: false,
    tier: 'lite',
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google.com',
    premium: false,
    tier: 'flash',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google.com',
    premium: false,
    tier: 'flash',
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    provider: 'google.com',
    premium: false,
    tier: 'lite',
  },
  // {
  //   id: 'gemini-2.0-flash-exp',
  //   name: 'Gemini 2.0 Flash Exp',
  //   premium: false,
  //   provider: 'google.com',
  //   tier: 'flash',
  // },
  // {
  //   id: 'gemini-2.0-flash-thinking-exp',
  //   name: 'Gemini 2.0 Flash Thinking Exp',
  //   premium: true,
  //   provider: 'google.com',
  //   tier: 'thinking',
  // },
  // {
  //   id: 'gemini-2.0-flash-thinking-exp-01-21',
  //   name: 'Gemini 2.0 Flash Thinking Exp 01 21',
  //   premium: true,
  //   provider: 'google.com',
  //   tier: 'thinking',
  // },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google.com',
    premium: true,
    tier: 'pro',
  },
  // {
  //   id: 'gemini-live-2.5-flash-preview',
  //   name: 'Gemini Live 2.5 Flash Preview',
  //   provider: 'google.com',
  //   premium: false,
  // },
  // {
  //   id: 'gemini-2.0-flash-preview-image-generation',
  //   name: 'Gemini 2.0 Flash Preview Image Generation',
  //   provider: 'google.com',
  //   premium: false,
  // },
  // {
  //   id: 'text-embedding-004',
  //   name: 'Gemini Text Embedding 004',
  //   provider: 'google.com',
  //   premium: false,
  // },
  // {
  //   id: 'gemini-embedding-001',
  //   name: 'Gemini Embedding 001',
  //   provider: 'google.com',
  //   premium: false,
  // },
  {
    id: 'qwen/qwen3-4b-thinking-2507',
    name: 'Qwen 3.4B Thinking 2507',
    provider: 'qwen.ai',
    premium: false,
    disabled: true,
    tier: 'thinking',
  },
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B Versatile',
    provider: 'meta.com',
    premium: false,
    disabled: true,
    tier: 'flash',
  },
  // {
  //   id: 'llama-3.1-8b-instant',
  //   name: 'Llama 3.1 8B Instant',
  //   provider: 'meta.com',
  //   premium: false,
  //   disabled: true,
  // },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'DeepSeek R1 Distill Llama 70B',
    provider: 'deepseek.com',
    premium: false,
    disabled: true,
    tier: 'thinking',
  },
  // {
  //   id: 'meta-llama/llama-4-scout-17b-16e-instruct',
  //   name: 'Meta Llama 4 Scout 17B 16E Instruct',
  //   provider: 'meta.com',
  //   premium: false,
  //   disabled: true,
  // },
  {
    id: 'mixtral-8x7b-32768',
    name: 'Mixtral 8x7B 32K',
    provider: 'mistral.ai',
    premium: false,
    disabled: true,
    tier: 'flash',
  },
  {
    id: 'gemma2-9b-it',
    name: 'Gemma 2 9B IT',
    provider: 'google.com',
    premium: false,
    disabled: true,
    tier: 'lite',
  },
  // {
  //   id: 'groq-compound-4-flash',
  //   name: 'Groq Compound 4 Flash',
  //   provider: 'groq.com',
  //   premium: false,
  //   disabled: true,
  // },
  {
    id: 'groq-compound-4',
    name: 'Groq Compound 4',
    provider: 'groq.com',
    premium: false,
    disabled: true,
    tier: 'pro',
  },
  {
    id: 'qwen-qwq-32b',
    name: 'Qwen QwQ 32B',
    provider: 'qwen.ai',
    premium: false,
    disabled: true,
    tier: 'thinking',
  },
  // {
  //   id: 'moonshotai/kimi-k2-instruct',
  //   name: 'MoonshotAI Kimi K2 Instruct',
  //   provider: 'moonshot.cn',
  //   premium: false,
  //   disabled: true,
  // },
  {
    id: 'gpt-oss-120b',
    name: 'GPT-OSS 120B',
    provider: 'openai.com',
    premium: false,
    disabled: true,
    tier: 'pro',
  },
]
